server {
    listen 80;
    server_name www.dental-school.education;

    return 308 https://dental-school.education$request_uri;
}

server {
    listen 80;
    server_name dental-school.education _;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Robots-Tag "noindex, nofollow, noarchive, noimageindex, nosnippet" always;

    location = /robots.txt {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
